name: instapost
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.5+2
  photo_view: ^0.9.2
  image_cropper: ^1.2.1
  cached_network_image: ^2.0.0
  flare_splash_screen: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  cloud_firestore: ^0.13.4
  provider: ^4.0.4
  image_picker: ^0.6.1+11
  firebase_storage: ^3.1.1
  path: ^1.6.4
  uuid: ^2.0.4
  time_formatter: ^1.0.0
  bot_toast: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
#  image_path: "assets/images/icon-128x128.png"
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.png"
  android: "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  
 # "images/logo.png"
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - fonts/splash.flr
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PTSans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
        - asset: fonts/PTSans-Italic.ttf
          style: italic
        - asset: fonts/PTSans-Bold.ttf
          weight: 700
    - family: Kaushan
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
        
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
